apiVersion: akash.overlock.network/v1alpha1
kind: SDL
metadata:
  name: simple-web
spec:
  providerConfigRef:
    name: default
  forProvider:
    version: "2.0"
    services:
      web:
        image: nginx:1.25
        expose:
          - port: 80
            as: 80
            to:
              - global: true
    profiles:
      compute:
        web:
          resources:
            cpu: "0.5"
            memory: "512Mi"
            storage:
              - size: "1Gi"
      placement:
        westcoast:
          attributes:
            region: us-west
          pricing:
            web:
              amount: 100
    deployment:
      web:
        profile: westcoast
        count: 1
