//go:build !ignore_autogenerated

/*
Copyright 2024 The Akash Provider Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveBid) DeepCopyInto(out *ActiveBid) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveBid.
func (in *ActiveBid) DeepCopy() *ActiveBid {
	if in == nil {
		return nil
	}
	out := new(ActiveBid)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActiveBid) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveBidList) DeepCopyInto(out *ActiveBidList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ActiveBid, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveBidList.
func (in *ActiveBidList) DeepCopy() *ActiveBidList {
	if in == nil {
		return nil
	}
	out := new(ActiveBidList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActiveBidList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveBidObservation) DeepCopyInto(out *ActiveBidObservation) {
	*out = *in
	if in.Price != nil {
		in, out := &in.Price, &out.Price
		*out = new(ActiveBidPriceStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveBidObservation.
func (in *ActiveBidObservation) DeepCopy() *ActiveBidObservation {
	if in == nil {
		return nil
	}
	out := new(ActiveBidObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveBidParameters) DeepCopyInto(out *ActiveBidParameters) {
	*out = *in
	in.DeploymentRef.DeepCopyInto(&out.DeploymentRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveBidParameters.
func (in *ActiveBidParameters) DeepCopy() *ActiveBidParameters {
	if in == nil {
		return nil
	}
	out := new(ActiveBidParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveBidPriceStatus) DeepCopyInto(out *ActiveBidPriceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveBidPriceStatus.
func (in *ActiveBidPriceStatus) DeepCopy() *ActiveBidPriceStatus {
	if in == nil {
		return nil
	}
	out := new(ActiveBidPriceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveBidReference) DeepCopyInto(out *ActiveBidReference) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveBidReference.
func (in *ActiveBidReference) DeepCopy() *ActiveBidReference {
	if in == nil {
		return nil
	}
	out := new(ActiveBidReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveBidSpec) DeepCopyInto(out *ActiveBidSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveBidSpec.
func (in *ActiveBidSpec) DeepCopy() *ActiveBidSpec {
	if in == nil {
		return nil
	}
	out := new(ActiveBidSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveBidStatus) DeepCopyInto(out *ActiveBidStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveBidStatus.
func (in *ActiveBidStatus) DeepCopy() *ActiveBidStatus {
	if in == nil {
		return nil
	}
	out := new(ActiveBidStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BidPolicy) DeepCopyInto(out *BidPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BidPolicy.
func (in *BidPolicy) DeepCopy() *BidPolicy {
	if in == nil {
		return nil
	}
	out := new(BidPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BidPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BidPolicyList) DeepCopyInto(out *BidPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BidPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BidPolicyList.
func (in *BidPolicyList) DeepCopy() *BidPolicyList {
	if in == nil {
		return nil
	}
	out := new(BidPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BidPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BidPolicyObservation) DeepCopyInto(out *BidPolicyObservation) {
	*out = *in
	if in.MatchedDeployments != nil {
		in, out := &in.MatchedDeployments, &out.MatchedDeployments
		*out = make([]DeploymentReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ActiveBidsManaged != nil {
		in, out := &in.ActiveBidsManaged, &out.ActiveBidsManaged
		*out = make([]ActiveBidReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SelectedBids != nil {
		in, out := &in.SelectedBids, &out.SelectedBids
		*out = make(map[string]ActiveBidReference, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.CreatedLeases != nil {
		in, out := &in.CreatedLeases, &out.CreatedLeases
		*out = make(map[string]LeaseReference, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.SelectionReasons != nil {
		in, out := &in.SelectionReasons, &out.SelectionReasons
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RejectedBids != nil {
		in, out := &in.RejectedBids, &out.RejectedBids
		*out = make([]RejectedBidInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastEvaluated != nil {
		in, out := &in.LastEvaluated, &out.LastEvaluated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BidPolicyObservation.
func (in *BidPolicyObservation) DeepCopy() *BidPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(BidPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BidPolicyParameters) DeepCopyInto(out *BidPolicyParameters) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.DeploymentRef != nil {
		in, out := &in.DeploymentRef, &out.DeploymentRef
		*out = new(DeploymentReference)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxPrice != nil {
		in, out := &in.MaxPrice, &out.MaxPrice
		*out = new(int64)
		**out = **in
	}
	if in.MinProviderScore != nil {
		in, out := &in.MinProviderScore, &out.MinProviderScore
		*out = new(int32)
		**out = **in
	}
	if in.RequiredAttributes != nil {
		in, out := &in.RequiredAttributes, &out.RequiredAttributes
		*out = make([]ProviderAttribute, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedProviders != nil {
		in, out := &in.ExcludedProviders, &out.ExcludedProviders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PreferredProviders != nil {
		in, out := &in.PreferredProviders, &out.PreferredProviders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WaitTime != nil {
		in, out := &in.WaitTime, &out.WaitTime
		*out = new(int32)
		**out = **in
	}
	if in.MaxBids != nil {
		in, out := &in.MaxBids, &out.MaxBids
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BidPolicyParameters.
func (in *BidPolicyParameters) DeepCopy() *BidPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(BidPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BidPolicySpec) DeepCopyInto(out *BidPolicySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BidPolicySpec.
func (in *BidPolicySpec) DeepCopy() *BidPolicySpec {
	if in == nil {
		return nil
	}
	out := new(BidPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BidPolicyStatus) DeepCopyInto(out *BidPolicyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BidPolicyStatus.
func (in *BidPolicyStatus) DeepCopy() *BidPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(BidPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentReference) DeepCopyInto(out *DeploymentReference) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentReference.
func (in *DeploymentReference) DeepCopy() *DeploymentReference {
	if in == nil {
		return nil
	}
	out := new(DeploymentReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaseReference) DeepCopyInto(out *LeaseReference) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaseReference.
func (in *LeaseReference) DeepCopy() *LeaseReference {
	if in == nil {
		return nil
	}
	out := new(LeaseReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAttribute) DeepCopyInto(out *ProviderAttribute) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAttribute.
func (in *ProviderAttribute) DeepCopy() *ProviderAttribute {
	if in == nil {
		return nil
	}
	out := new(ProviderAttribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RejectedBidInfo) DeepCopyInto(out *RejectedBidInfo) {
	*out = *in
	if in.RejectedAt != nil {
		in, out := &in.RejectedAt, &out.RejectedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RejectedBidInfo.
func (in *RejectedBidInfo) DeepCopy() *RejectedBidInfo {
	if in == nil {
		return nil
	}
	out := new(RejectedBidInfo)
	in.DeepCopyInto(out)
	return out
}
