name: Publish Provider Package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  publish-provider-package:
    uses: crossplane-contrib/provider-workflows/.github/workflows/publish-provider.yml@main
    with:
      cleanup-disk: true
      go-version: '1.25'
      repository: provider-akash
      version: ${{ github.ref_name }}
      registry_org: overlock-network
    secrets:
      GHCR_PAT: ${{ secrets.GITHUB_TOKEN }}
      XPKG_MIRROR_ACCESS_ID: ${{ secrets.XPKG_ACCESS_ID }}
      XPKG_MIRROR_TOKEN: ${{ secrets.XPKG_TOKEN }}

  append-marketplace-extensions:
    needs: publish-provider-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install up CLI
        run: |
          mkdir -p "$HOME/.local/bin"
          curl -sL https://cli.upbound.io | UP_CHANNEL=stable sh
          mv up "$HOME/.local/bin/up"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - run: up version
      - uses: docker/login-action@v3
        with:
          registry: xpkg.upbound.io
          username: ${{ secrets.XPKG_ACCESS_ID }}
          password: ${{ secrets.XPKG_TOKEN }}
      - name: Append marketplace extensions
        run: |
          up alpha xpkg append \
            --extensions-root=./extensions \
            xpkg.upbound.io/overlock-network/provider-akash:${{ github.ref_name }}
